Models/Camiseta.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VintageStuff.Models
{
    public class Camiseta
    {
        public Camiseta()
        {
        }
        public Camiseta(string marca, string modelo)
        {
            Marca = marca;
            Modelo = modelo;
        }
        public int Id { get; set; }
               
        [System.ComponentModel.DataAnnotations.Display(Description = "Esta es la marca")]
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public byte[] Foto { get; set; }
        [NotMapped]
        [Display(Name = "Fotografía")]
        public string FotoBase64 { get; set; }

    }
}

Controllers/CamisetasController.cs
using System;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VintageStuff.Data;
using VintageStuff.Models;
using VintageStuff.ViewModels;



namespace VintageStuff.Controllers
{
    public class CamisetasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CamisetasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Camisetas
        public async Task<IActionResult> Index()
        {
            var camisetas = await _context.Camisetas.ToListAsync();
            camisetas.ForEach(cadaCamiseta => cadaCamiseta.FotoBase64 = $"data:image/png;base64,{Convert.ToBase64String(cadaCamiseta.Foto)}");
            return View(camisetas);
        }
       

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Comprar(int? id )
        {
            if(id == null)
            {
                return NotFound();
            }
            var usuarioActual = 1; //ToDo: Obtener el usuario actual logueado
            var persona = await _context.Personas.FirstOrDefaultAsync(p => p.Id == usuarioActual);
            var camisetaSeleccionada = await _context.Camisetas.FirstOrDefaultAsync(c => c.Id == id);
            if(camisetaSeleccionada == null)
            {
                return NotFound();
            }
            persona.Camisetas.Add(camisetaSeleccionada);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));


        }


        // GET: Camisetas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var camiseta = await _context.Camisetas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (camiseta == null)
            {
                return NotFound();
            }

            return View(camiseta);
        }

        // GET: Camisetas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Camisetas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CamisaViewModel camisaViewModel)
        {
            if (ModelState.IsValid)
            {
                Camiseta camisa = new Camiseta();
                camisa.Marca = camisaViewModel.Marca;
                camisa.Modelo = camisaViewModel.Modelo;
                camisa.Foto = ConvertirArregloByte(camisaViewModel.Foto);
                _context.Add(camisa);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(camisaViewModel);
        }

        private byte[] ConvertirArregloByte(IFormFile formFile)
        {
            if (formFile != null)
            {
                using (var memoryStream = new MemoryStream())
                {
                    formFile.CopyTo(memoryStream);
                    var tamanoMaximo = 2097152; //Si el archivo es mas grande usar streaming
                    if (memoryStream.Length < tamanoMaximo)
                        return memoryStream.ToArray();
                }
            }
            return null;
        }

        // GET: Camisetas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var camiseta = await _context.Camisetas.FindAsync(id);
            if (camiseta == null)
            {
                return NotFound();
            }
            return View(camiseta);
        }

        // POST: Camisetas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Marca,Modelo,Id")] Camiseta camiseta)
        {
            if (id != camiseta.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(camiseta);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CamisetaExists(camiseta.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(camiseta);
        }

        // GET: Camisetas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var camiseta = await _context.Camisetas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (camiseta == null)
            {
                return NotFound();
            }

            return View(camiseta);
        }

        // POST: Camisetas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var camiseta = await _context.Camisetas.FindAsync(id);
            _context.Camisetas.Remove(camiseta);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CamisetaExists(int id)
        {
            return _context.Camisetas.Any(e => e.Id == id);
        }
    }
}

Views/Camisetas/Comprar.cshtml
@model IEnumerable<VintageStuff.Models.Camiseta>

@{
    ViewData["Title"] = "Comprar";
}

<h1>Compre sus más bonitas camisetas</h1>
<table>
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Modelo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FotoBase64)
            </th>
            <th>Comando</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var articulo in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(x => articulo.Marca)<!--Aquí van los datos de la marca-->
            </td>
            <td>
                @Html.DisplayFor(x => articulo.Modelo)<!--Aquí van los datos del modelo-->
            </td>
            <td>
                <img src="@articulo.FotoBase64" alt="Fotografía no encontrada" />
            </td>
            <td>
                <form asp-action="Comprar/@articulo.Id">
                    <input type="submit" value="Comprar" class="btn btn-primary" />
                </form>
            </td>
        </tr>
        }
    </tbody>
</table>

Views/Camisetas/Create.cshtml
@model VintageStuff.ViewModels.CamisaViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

@using (Html.BeginForm("Create", "Camisetas", FormMethod.Post, new { enctype = "multipart/form-data" }))

    @Html.AntiForgeryToken()

<h4>Camiseta</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
                <div class="rounded-circle" height="10" width="10" asp-append-version="true">
                <label asp-for="Foto" class="control-label"></label>
                <input asp-for="Foto" class="custom-file-input" id="customFile" />
                <label class="custom-file-label" for="customFile">Escoje un archivo</label>
                <span asp-validation-for="Foto" class="text-danger"></span>
             </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Volver a la lista</a>
    </div>

    @section Scripts {
        <script type="text/javascript">
            $(".custom-file-input").on("change", function () {
                var nombreArchivo = $(this).val().split("\\").pop();
                $(this).siblings(".custom-file-label").addClass("selected").html(nombreArchivo);
            });
        </script>
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

Views/Camisetas/Delete.cshtml
@model VintageStuff.Models.Camiseta

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Camiseta</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Camisetas/Details.cshtml
@model VintageStuff.Models.Camiseta

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Camiseta</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Marca)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Marca)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Modelo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Modelo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Camisetas/Edit.cshtml
@model VintageStuff.Models.Camiseta

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Camiseta</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Marca" class="control-label"></label>
                <input asp-for="Marca" class="form-control" />
                <span asp-validation-for="Marca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modelo" class="control-label"></label>
                <input asp-for="Modelo" class="form-control" />
                <span asp-validation-for="Modelo" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Camisetas/Index.cshtml
@model IEnumerable<VintageStuff.Models.Camiseta>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Modelo)
            </th>
            <th>
            <th>
                @Html.DisplayNameFor(model => model.FotoBase64)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Marca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Modelo)
            </td>
            <td>
                <img src="@item.FotoBase64" alt="Fotografía no encontrada" />
            </td>
            <td>
              
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
            </td>
        </tr>
}
    </tbody>
</table>